### ISSUE TITLE
ImportError: cannot import name '_enable_xformers' from 'sfast.compilers.stable_diffusion_pipeline_compiler' 

### ISSUE THREAD

**Issue by onefish51** [gameltb/ComfyUI_stable_fast#11]
```python
`sfast.compilers.stable_diffusion_pipeline_compiler` is deprecated. Please use `sfast.compilers.diffusion_pipeline_compiler` instead.
ComfyUI_stable_fast: StableFast node import failed.
Traceback (most recent call last):
  File "/app/custom_nodes/ComfyUI_stable_fast/__init__.py", line 10, in <module>
    from .node import ApplyStableFastUnet
  File "/app/custom_nodes/ComfyUI_stable_fast/node.py", line 4, in <module>
    from .module.sfast_pipeline_compiler import build_lazy_trace_module
  File "/app/custom_nodes/ComfyUI_stable_fast/module/sfast_pipeline_compiler.py", line 6, in <module>
    from sfast.compilers.stable_diffusion_pipeline_compiler import (
ImportError: cannot import name '_enable_xformers' from 'sfast.compilers.stable_diffusion_pipeline_compiler' (/opt/conda/lib/python3.10/site-packages/sfast/compilers/stable_diffusion_pipeline_compiler.py)
```

as it said "`sfast.compilers.stable_diffusion_pipeline_compiler` is deprecated. Please use `sfast.compilers.diffusion_pipeline_compiler` "

**Comment by gameltb** [comment]
Updated.

**Comment by onefish51** [comment]
OK
