### ISSUE TITLE
stable-fast version 1.0.0 does not support Windows system？

### ISSUE THREAD

**Issue by vbqgyy** [gameltb/ComfyUI_stable_fast#14]
win10 system
installation environment：
triton==2.0.0
torch==2.1.0+cu118
xformers==0.0.22.post7+cu118
CUDA==11.8
Python==3.10.6

ComfyUI_stable_fast  
After updating the latest version：

Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 101, in apply_stable_fast
    config = gen_stable_fast_config()
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 22, in gen_stable_fast_config
    import triton
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\__init__.py", line 13, in <module>
    from . import language
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\language\__init__.py", line 2, in <module>
    from . import core, extern, libdevice, random
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\language\core.py", line 1141, in <module>
    def abs(x):
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 386, in jit
    return JITFunction(args[0], **kwargs)
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 315, in __init__
    self.run = self._make_launcher()
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 282, in _make_launcher
    scope = {"version_key": version_key(), "get_cuda_stream": get_cuda_stream,
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 82, in version_key    with open(triton._C.libtriton.__file__, "rb") as f:
AttributeError: partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)

**Comment by gameltb** [comment]
You should not install `triton` on windows, stable fast may require linux or WSL to get the best results.

**Comment by vbqgyy** [comment]
Thank you for your reply, I will try wsl2.

**Comment by dancemanUK** [comment]
try triton-2.0.0-cp310-cp310-win_amd64.whl

**Comment by dancemanUK** [comment]
windows  use  whl
https://github.com/chengzeyi/stable-fast/releases/tag/v1.0.1
