### ISSUE TITLE
Test TensorRT VAEDecode failed !

### ISSUE THREAD

**Issue by onefish51** [gameltb/ComfyUI_stable_fast#15]
```bash 
python main.py --listen 0.0.0.0 --port 5000 --disable-xformers
```

workflow :
![image](https://github.com/gameltb/ComfyUI_stable_fast/assets/21029719/8e888f1c-5fc2-4325-8df4-1ee5ecd10470)
[workflow_VAEDecode_trt.json](https://github.com/gameltb/ComfyUI_stable_fast/files/13776232/workflow_VAEDecode_trt.json)

an error thrown :
```bash 
Building TensorRT engine for : /app/custom_nodes/ComfyUI_stable_fast/tensorrt_engine_cache/73be59a4c039b7874c93c67755495ca5abe002922633db0e26a24b1e2146724a.trt
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[E] In node 457 with name: /decoder/block_1/norm1/InstanceNormalization and operator: InstanceNormalization (importInstanceNormalization): INVALID_NODE: Assertion failed: (inputDataType == DataType::kFLOAT || inputDataType == DataType::kHALF): Inputs must be either FLOAT or FLOAT16. Input type is BF16.
[!] Could not parse ONNX correctly
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/app/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/app/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/app/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/app/nodes.py", line 267, in decode
    return (vae.decode(samples["samples"]), )
  File "/app/comfy/sd.py", line 237, in decode
    pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(samples).to(self.output_device).float() + 1.0) / 2.0, min=0.0, max=1.0)
  File "/app/custom_nodes/ComfyUI_stable_fast/tensorrt_node.py", line 350, in __call__
    self.warmup(samples_in)
  File "/app/custom_nodes/ComfyUI_stable_fast/tensorrt_node.py", line 343, in warmup
    self(warmup_samples)
  File "/app/custom_nodes/ComfyUI_stable_fast/tensorrt_node.py", line 368, in __call__
    pixel_samples[x : x + batch_number] = self.tensorrt_module(
  File "/app/custom_nodes/ComfyUI_stable_fast/module/tensorrt_wrapper.py", line 152, in __call__
    engine = gen_engine(
  File "/app/custom_nodes/ComfyUI_stable_fast/module/tensorrt_wrapper.py", line 294, in gen_engine
    engine.build(
  File "/app/custom_nodes/ComfyUI_stable_fast/module/tensorrt_utilities.py", line 284, in build
    network = network_from_onnx_bytes(
  File "<string>", line 3, in network_from_onnx_bytes
  File "/opt/conda/lib/python3.10/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/polygraphy/backend/trt/loader.py", line 185, in call_impl
    trt_util.check_onnx_parser_errors(parser, success)
  File "/opt/conda/lib/python3.10/site-packages/polygraphy/backend/trt/util.py", line 83, in check_onnx_parser_errors
    G_LOGGER.critical("Could not parse ONNX correctly")
  File "/opt/conda/lib/python3.10/site-packages/polygraphy/logger/logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Could not parse ONNX correctly
```
besides TensorRT Unet run is OK !

**Comment by gameltb** [comment]
Add `--fp16-vae` to ComfyUI .

**Comment by onefish51** [comment]
yes!
