### ISSUE TITLE
ERROR IMPORTING sfast

### ISSUE THREAD

**Issue by Piscabo** [gameltb/ComfyUI_stable_fast#24]
I don't know what this means. I think this repository is too old to make use of the new wheels and touch.
***ERROR IMPORTING sfast._C***
Unable to load stable-fast C extension.
Is it compatible with your PyTorch installation?
Or is it compatible with your CUDA version?

ComfyUI_stable_fast: StableFast node import failed.
Traceback (most recent call last):
  File "H:\ComfyUI\custom_nodes\ComfyUI_stable_fast\__init__.py", line 10, in <module>
    from .node import ApplyStableFastUnet
  File "H:\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 2, in <module>
    from sfast.compilers.diffusion_pipeline_compiler import CompilationConfig
  File "C:\comfyVENV\Lib\site-packages\sfast\__init__.py", line 23, in <module>
    import sfast._C as _C
ImportError: DLL load failed while importing _C: The specified procedure could not be found.

**Comment by Milor123** [comment]
I have the same issue

**Comment by dancemanUK** [comment]
### [END] ComfyUI AlekPet Nodes ###
FizzleDorf Custom Nodes: Loaded

***ERROR IMPORTING sfast._C***
Unable to load stable-fast C extension.
Is it compatible with your PyTorch installation?
Or is it compatible with your CUDA version?

ComfyUI_stable_fast: StableFast node import failed.
Traceback (most recent call last):
  File "G:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_stable_fast\__init__.py", line 10, in <module>
    from .node import ApplyStableFastUnet
  File "G:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 2, in <module>
    from sfast.compilers.diffusion_pipeline_compiler import CompilationConfig
  File "G:\Blender_ComfyUI\python_embeded\lib\site-packages\sfast\__init__.py", line 23, in <module>
    import sfast._C as _C
ImportError: DLL load failed while importing _C: 找不到指定的程序。
[tinyterraNodes] Loaded


me too

**Comment by Milor123** [comment]
Any solution?

**Comment by liho00** [comment]
same issue here
