### ISSUE TITLE
RuntimeError: RuntimeError: Failed to find C compiler. Please specify via CC environment variable.

### ISSUE THREAD

**Issue by RafaRed** [gameltb/ComfyUI_stable_fast#4]
Just followed the instructions to install on confyui

```Loading 1 new model
  0%|          | 0/4 [00:00<?, ?it/s]/root/miniconda3/lib/python3.11/site-packages/sfast/utils/flat_tensors.py:157: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  obj_type = tensors[start].item()
/root/miniconda3/lib/python3.11/site-packages/sfast/utils/flat_tensors.py:216: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  size = tensors[start].item()
/root/miniconda3/lib/python3.11/site-packages/sfast/utils/flat_tensors.py:226: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  size = tensors[start].item()
/root/miniconda3/lib/python3.11/site-packages/sfast/utils/flat_tensors.py:212: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return bytes(tensors[start].tolist()), start + 1
/root/miniconda3/lib/python3.11/site-packages/sfast/utils/flat_tensors.py:203: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return int(tensors[start].item()), start + 1
/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py:619: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert y.shape[0] == x.shape[0]
/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py:125: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py:83: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
/root/miniconda3/lib/python3.11/site-packages/sfast/utils/flat_tensors.py:21: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  return torch.tensor([num], dtype=torch.int64)
  0%|          | 0/4 [03:07<?, ?it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/nodes.py", line 1237, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/nodes.py", line 1207, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/hacky.py", line 22, in informative_sample
    raise e
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/hacky.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 692, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 598, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 558, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/k_diffusion/sampling.py", line 745, in sample_lcm
    denoised = model(x, sigmas[i] * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 275, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 265, in forward
    return self.apply_model(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 262, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 250, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 226, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/g/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_stable_fast/node.py", line 65, in __call__
    return self.stable_fast_model(input_x, timestep_, **c)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/sfast/jit/trace_helper.py", line 108, in forward
    outputs = self.module(*convert_to_flat_tensors((args, kwargs)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/sfast/cuda/graphs.py", line 29, in dynamic_graphed_callable
    cached_callable = simple_make_graphed_callable(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/sfast/cuda/graphs.py", line 44, in simple_make_graphed_callable
    return make_graphed_callable(callable,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/sfast/cuda/graphs.py", line 73, in make_graphed_callable
    callable(*copy.deepcopy(example_inputs),
  File "/root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):

graph(%input, %num_groups, %weight, %bias, %eps, %cudnn_enabled):
    %y : Tensor = sfast_triton::group_norm_silu(%input, %num_groups, %weight, %bias, %eps)
                  ~~~~~~~~~~~~ <--- HERE
    return (%y)
RuntimeError: RuntimeError: Failed to find C compiler. Please specify via CC environment variable.

At:
  /root/miniconda3/lib/python3.11/site-packages/triton/common/build.py(73): _build
  /root/miniconda3/lib/python3.11/site-packages/triton/compiler/make_launcher.py(39): make_stub
  /root/miniconda3/lib/python3.11/site-packages/triton/compiler/compiler.py(425): compile
  <string>(63): group_norm_4d_channels_last_forward_collect_stats_kernel
  /root/miniconda3/lib/python3.11/site-packages/sfast/triton/__init__.py(35): new_func
  /root/miniconda3/lib/python3.11/site-packages/triton/runtime/autotuner.py(81): kernel_call
  /root/miniconda3/lib/python3.11/site-packages/triton/testing.py(104): do_bench
  /root/miniconda3/lib/python3.11/site-packages/triton/runtime/autotuner.py(84): _bench
  /root/miniconda3/lib/python3.11/site-packages/triton/runtime/autotuner.py(100): <dictcomp>
  /root/miniconda3/lib/python3.11/site-packages/triton/runtime/autotuner.py(100): run
  /root/miniconda3/lib/python3.11/site-packages/sfast/triton/__init__.py(35): new_func
  /root/miniconda3/lib/python3.11/site-packages/sfast/triton/ops/group_norm.py(318): group_norm_forward
  /root/miniconda3/lib/python3.11/site-packages/sfast/triton/torch_ops.py(186): forward
  /root/miniconda3/lib/python3.11/site-packages/torch/autograd/function.py(539): apply
  /root/miniconda3/lib/python3.11/site-packages/sfast/triton/torch_ops.py(224): group_norm_silu
  /root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py(1527): _call_impl
  /root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
  /root/miniconda3/lib/python3.11/site-packages/sfast/cuda/graphs.py(73): make_graphed_callable
  /root/miniconda3/lib/python3.11/site-packages/sfast/cuda/graphs.py(44): simple_make_graphed_callable
  /root/miniconda3/lib/python3.11/site-packages/sfast/cuda/graphs.py(29): dynamic_graphed_callable
  /root/miniconda3/lib/python3.11/site-packages/sfast/jit/trace_helper.py(108): forward
  /root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py(1527): _call_impl
  /root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
  /mnt/g/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_stable_fast/node.py(65): __call__
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py(226): calc_cond_uncond_batch
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py(250): sampling_function
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py(262): apply_model
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py(265): forward
  /root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py(1527): _call_impl
  /root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py(275): forward
  /root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py(1527): _call_impl
  /root/miniconda3/lib/python3.11/site-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/k_diffusion/sampling.py(745): sample_lcm
  /root/miniconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py(115): decorate_context
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py(558): sample
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py(598): sample
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py(692): sample
  /mnt/g/ComfyUI_windows_portable/ComfyUI/comfy/sample.py(100): sample
  /mnt/g/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/hacky.py(9): informative_sample
  /mnt/g/ComfyUI_windows_portable/ComfyUI/nodes.py(1207): common_ksampler
  /mnt/g/ComfyUI_windows_portable/ComfyUI/nodes.py(1237): sample
  /mnt/g/ComfyUI_windows_portable/ComfyUI/execution.py(76): map_node_over_list
  /mnt/g/ComfyUI_windows_portable/ComfyUI/execution.py(83): get_output_data
  /mnt/g/ComfyUI_windows_portable/ComfyUI/execution.py(153): recursive_execute
  /mnt/g/ComfyUI_windows_portable/ComfyUI/execution.py(136): recursive_execute
  /mnt/g/ComfyUI_windows_portable/ComfyUI/execution.py(136): recursive_execute
  /mnt/g/ComfyUI_windows_portable/ComfyUI/execution.py(377): execute
  /mnt/g/ComfyUI_windows_portable/ComfyUI/main.py(95): prompt_worker
  /root/miniconda3/lib/python3.11/threading.py(975): run
  /root/miniconda3/lib/python3.11/threading.py(1038): _bootstrap_inner
  /root/miniconda3/lib/python3.11/threading.py(995): _bootstrap



Prompt executed in 190.37 seconds```

**Comment by gameltb** [comment]
You may need to install CUDA Toolkit and gcc in WSL.

**Comment by RafaRed** [comment]
@gameltb Thank you, it was really missing CUDA.
I Forgot that I made a clean up on WSL.

Now its working, even with triton. :)
