### ISSUE TITLE
ModuleNotFoundError: No module named 'sfast'

### ISSUE THREAD

**Issue by Nicoolodion2** [gameltb/ComfyUI_stable_fast#8]
Wheels have build correctly, but the extension fails to import...
I am running on Windows.

![Screenshot 2023-12-01 164015](https://github.com/gameltb/ComfyUI_stable_fast/assets/146431041/fa6722b3-22b1-496c-8c5a-c7cb2a958e9e)

**Comment by gameltb** [comment]
It looks like stable_fast is not installed in the python environment where comfy is running.
You need to install it through your `python_embedded\python.exe`.

**Comment by Nicoolodion2** [comment]
> It looks like stable_fast is not installed in the python environment where comfy is running. You need to install it through your `python_embedded\python.exe`.

Dumb question, but how do I do that? It always give me "Syntaxerror: invalid syntax"

**Comment by gameltb** [comment]
Sorry, I don't know much about python embedded.
But you can try use `python_embeded/Scripts/pip.exe` replace `pip` in command and see if it work. 
or use `python_embedded\python.exe -m pip`.

**Comment by Nicoolodion2** [comment]
Okay, this worked partly now. I now get only this error: No module named 'onnx' And yes, It is installed...

**Comment by gameltb** [comment]
I updated `tensorrt` branch. you can try it. It still in test so may only simple workflow work.
There may be problems with modifying the resolution, batch, and prompt words. I'll try to fix it in the next few days.

**Comment by LabMember01** [comment]
> > It looks like stable_fast is not installed in the python environment where comfy is running. You need to install it through your `python_embedded\python.exe`.
> 
> Dumb question, but how do I do that? It always gives me "Syntaxerror: invalid syntax"

How did you get this running? I'm also not much of a programmer and have the same issue. syntaxerror , not sure what I'm doing wrong :p

**Comment by Nicoolodion2** [comment]
> > > It looks like stable_fast is not installed in the python environment where comfy is running. You need to install it through your `python_embedded\python.exe`.
> > 
> > 
> > Dumb question, but how do I do that? It always gives me "Syntaxerror: invalid syntax"
> 
> How did you get this running? I'm also not much of a programmer and have the same issue. syntaxerror , not sure what I'm doing wrong :p

I followed the install turtorial again, but this time always used in normal cmd "python_embedded\python.exe" and then the normal pip install ... I also manually installed some things I got an error, but didn't follow an pattern. 
Sorry, but I can't explain it better, since i don't understand myself completly what I did.

**Comment by LabMember01** [comment]
> > > > It looks like stable_fast is not installed in the python environment where comfy is running. You need to install it through your `python_embedded\python.exe`.
> > > 
> > > 
> > > Dumb question, but how do I do that? It always gives me "Syntaxerror: invalid syntax"
> > 
> > 
> > How did you get this running? I'm also not much of a programmer and have the same issue. syntaxerror , not sure what I'm doing wrong :p
> 
> I followed the install turtorial again, but this time always used in normal cmd "python_embedded\python.exe" and then the normal pip install ... I also manually installed some things I got an error, but didn't follow an pattern. Sorry, but I can't explain it better, since i don't understand myself completly what I did.

So basically reinstalled Comfy? I think I'll have to back things up first :(

**Comment by Nicoolodion2** [comment]
> > > > > It looks like stable_fast is not installed in the python environment where comfy is running. You need to install it through your `python_embedded\python.exe`.
> > > > 
> > > > 
> > > > Dumb question, but how do I do that? It always gives me "Syntaxerror: invalid syntax"
> > > 
> > > 
> > > How did you get this running? I'm also not much of a programmer and have the same issue. syntaxerror , not sure what I'm doing wrong :p
> > 
> > 
> > I followed the install turtorial again, but this time always used in normal cmd "python_embedded\python.exe" and then the normal pip install ... I also manually installed some things I got an error, but didn't follow an pattern. Sorry, but I can't explain it better, since i don't understand myself completly what I did.
> 
> So basically reinstalled Comfy? I think I'll have to back things up first :(

No, the normal installation tutorial from the extension. Not comfyui. You don't have to reinstall comfyui, since that wouldn't change much. Follow the normal installation tutorial, but always with the "python_embedded\python.exe" at the start (cd to the folder where the subfolder "python_embedded" is)

**Comment by Nicoolodion2** [comment]
Okay, I think I forgot to mention something. The correct command is "python_embeded\python.exe -s -m pip install" (and then the normal names), sorry my bad.

And heres a small update to my problem (updates didn't fix anything). From https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/82 and https://github.com/NVIDIA/TensorRT/issues/2739 I guess that some value is wrong set? Although I don't have any idea on how to fix it...

**Comment by Nicoolodion2** [comment]
Okay, newest version seems to fix that problem, but now I get some different error... I now get to the building engine part, but then I get that error: 
[E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::4048] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[/diffusion_model/input_blocks.1.0/in_layers/in_layers.0/Constant_1_output_0 + ONNXTRT_unsqueezeTensor.../diffusion_model/input_blocks.1.0/in_layers/in_layers.1/Mul]}.)

(Tell me if I should just open a new issue for that)

**Comment by gameltb** [comment]
you can try run comfyui with `--force-fp16`

**Comment by Nicoolodion2** [comment]
> you can try run comfyui with `--force-fp16`

Doesn't change anything

**Comment by gameltb** [comment]
> > you can try run comfyui with `--force-fp16`
> 
> Doesn't change anything

Sorry I'm not sure what caused this error, maybe I'll test with windows later and now I'm still working on the feature.

**Comment by gameltb** [comment]
> Okay, newest version seems to fix that problem, but now I get some different error... I now get to the building engine part, but then I get that error: [E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::4048] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[/diffusion_model/input_blocks.1.0/in_layers/in_layers.0/Constant_1_output_0 + ONNXTRT_unsqueezeTensor.../diffusion_model/input_blocks.1.0/in_layers/in_layers.1/Mul]}.)
> 
> (Tell me if I should just open a new issue for that)

I've updated the code and it should fix some bugs caused by insufficient video memory when building the engine. Probably solve this problem

**Comment by Nicoolodion2** [comment]
Okay, maybe I am stupid and cursed. Tried the newest git pull, and it still gives me the same error (after about 4% of building the model) Although I have no Idea what you mean with "Set patch_type to UNET_BLOCK"?

**Comment by gameltb** [comment]
![image](https://github.com/gameltb/ComfyUI_stable_fast/assets/4462385/109da9bc-474d-4e4c-ae63-509051bd8741)
I mean patch_type here.
But I've updated it, so it's okay if it's not set like this.
Also, can you paste the log from the beginning of the `Building TensorRT engine for ......` appear, maybe I can figure out why this error is happening.

**Comment by nanaj96** [comment]
> Wheels have build correctly, but the extension fails to import... I am running on Windows. There is not any other relevant error (not connected)
> 
> ![Screenshot 2023-12-01 164015](https://private-user-images.githubusercontent.com/146431041/287311878-fa6722b3-22b1-496c-8c5a-c7cb2a958e9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTUzNTgsIm5iZiI6MTcwMjMxNTA1OCwicGF0aCI6Ii8xNDY0MzEwNDEvMjg3MzExODc4LWZhNjcyMmIzLTIyYjEtNDk2Yy04YzVhLWM3Y2IyYTk1OGU5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNzE3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWIxZTg5NWQyYmE2MDUxNGFkZTdiOTVjZTdjMGUwZGQwOTgzMDgyN2RlZmZhMzU0M2U1YjY2N2ZiMjAxZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cGTyVn1BVq_xS6xDHKCqdxb4kmzD12jX0NpP7SL_njc)

have you found the solution?

**Comment by Nicoolodion2** [comment]
Fuck... Fuck. Fuck! I am stupid... I was the whole time on the tensorrt branch. It didn't receive any updates. It guess it is obsolete now. Everything worked perfectly as I changed to the main branch. Tensorrt works, but only if I use "patch_type" = Unet and not Unet_block. Apply tensorRT vae decoder doesn't work, but I am unsure what it even does. But it works so good :)

**Comment by Nicoolodion2** [comment]
> > Wheels have build correctly, but the extension fails to import... I am running on Windows. There is not any other relevant error (not connected)
> > ![Screenshot 2023-12-01 164015](https://private-user-images.githubusercontent.com/146431041/287311878-fa6722b3-22b1-496c-8c5a-c7cb2a958e9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTUzNTgsIm5iZiI6MTcwMjMxNTA1OCwicGF0aCI6Ii8xNDY0MzEwNDEvMjg3MzExODc4LWZhNjcyMmIzLTIyYjEtNDk2Yy04YzVhLWM3Y2IyYTk1OGU5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNzE3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWIxZTg5NWQyYmE2MDUxNGFkZTdiOTVjZTdjMGUwZGQwOTgzMDgyN2RlZmZhMzU0M2U1YjY2N2ZiMjAxZmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cGTyVn1BVq_xS6xDHKCqdxb4kmzD12jX0NpP7SL_njc)
> 
> have you found the solution?

I installed some things I believe with "python_embeded\python.exe -s -m pip install". But I have no Idea what exactly I have done...

**Comment by Piscabo** [comment]
I have the same problem:
ComfyUI_stable_fast: StableFast node import failed.
Traceback (most recent call last):
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast\__init__.py", line 10, in <module>
    from .node import ApplyStableFastUnet
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 2, in <module>
    from sfast.compilers.stable_diffusion_pipeline_compiler import CompilationConfig
**ModuleNotFoundError: No module named 'sfast'**

**Comment by Nicoolodion2** [comment]
> I have the same problem: ComfyUI_stable_fast: StableFast node import failed. Traceback (most recent call last): File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast__init__.py", line 10, in from .node import ApplyStableFastUnet File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 2, in from sfast.compilers.stable_diffusion_pipeline_compiler import CompilationConfig **ModuleNotFoundError: No module named 'sfast'**

So, you need to install it to the enviroment. Follow the installation again, but this time use `python_embeded\python.exe -s -m pip install` (and then what would be after the normal pip install) This should bring you a step closer. Then you maybe have to install some things manually... Maybe some knowledge (or pain) required?

**Comment by Piscabo** [comment]
> > I have the same problem: ComfyUI_stable_fast: StableFast node import failed. Traceback (most recent call last): File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast__init__.py", line 10, in from .node import ApplyStableFastUnet File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 2, in from sfast.compilers.stable_diffusion_pipeline_compiler import CompilationConfig **ModuleNotFoundError: No module named 'sfast'**
> 
> So, you need to install it to the enviroment. Follow the installation again, but this time use `python_embeded\python.exe -s -m pip install` (and then what would be after the normal pip install) This should bring you a step closer. Then you maybe have to install some things manually... Maybe some knowledge (or pain) required?

I know a bit and have been doing some stuff. No more other errors. But is unable to install sfast:
(venv) A:\AI_Files>python.exe -s -m pip install sfast
ERROR: Could not find a version that satisfies the requirement sfast (from versions: none)
ERROR: No matching distribution found for sfast

**Comment by Nicoolodion2** [comment]
> > > I have the same problem: ComfyUI_stable_fast: StableFast node import failed. Traceback (most recent call last): File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast__init__.py", line 10, in from .node import ApplyStableFastUnet File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 2, in from sfast.compilers.stable_diffusion_pipeline_compiler import CompilationConfig **ModuleNotFoundError: No module named 'sfast'**
> > 
> > 
> > So, you need to install it to the enviroment. Follow the installation again, but this time use `python_embeded\python.exe -s -m pip install` (and then what would be after the normal pip install) This should bring you a step closer. Then you maybe have to install some things manually... Maybe some knowledge (or pain) required?
> 
> I know a bit and have been doing some stuff. No more other errors. But is unable to install sfast: (venv) A:\AI_Files>python.exe -s -m pip install sfast ERROR: Could not find a version that satisfies the requirement sfast (from versions: none) ERROR: No matching distribution found for sfast

I don't think sfast was some seperat thing to install. I guess it was an part of Tensorrt (`pip install --pre --upgrade --extra-index-url https://pypi.nvidia.com tensorrt`)

**Comment by Piscabo** [comment]
> > > > I have the same problem: ComfyUI_stable_fast: StableFast node import failed. Traceback (most recent call last): File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast__init__.py", line 10, in from .node import ApplyStableFastUnet File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 2, in from sfast.compilers.stable_diffusion_pipeline_compiler import CompilationConfig **ModuleNotFoundError: No module named 'sfast'**
> > > 
> > > 
> > > So, you need to install it to the enviroment. Follow the installation again, but this time use `python_embeded\python.exe -s -m pip install` (and then what would be after the normal pip install) This should bring you a step closer. Then you maybe have to install some things manually... Maybe some knowledge (or pain) required?
> > 
> > 
> > I know a bit and have been doing some stuff. No more other errors. But is unable to install sfast: (venv) A:\AI_Files>python.exe -s -m pip install sfast ERROR: Could not find a version that satisfies the requirement sfast (from versions: none) ERROR: No matching distribution found for sfast
> 
> I don't think sfast was some seperat thing to install. I guess it was an part of Tensorrt (`pip install --pre --upgrade --extra-index-url https://pypi.nvidia.com tensorrt`)

No luck with that, installed successfully. But I still have that error. Can you check in your environment where that module is? 'sfast'

**Comment by Nicoolodion2** [comment]
> No luck with that, installed successfully. But I still have that error. Can you check in your environment where that module is? 'sfast'

Searched through the files, and I don't find anything called like that (or folders)

**Comment by Nicoolodion2** [comment]
Oh, maybe it is worthwhile to notice that sfast is just short for stable fast...

**Comment by Nicoolodion2** [comment]
Oh maybe I have an Idea what the problem could be... Have you installed https://github.com/chengzeyi/stable-fast?tab=readme-ov-file#installation that too?

**Comment by Piscabo** [comment]
@Nicoolodion2 Fixed my problem... I had that installed. Thank you for your help.

**Comment by p80ric** [comment]
Would be awesome to have a prestartup_script.py file to install all the requirements needed to get this running. 
I have tried (after downloading the whl file):

pip3 install --index-url https://download.pytorch.org/whl/cu121 'torch>=2.1.0' 'xformers>=0.0.22' 'triton>=2.1.0' 'diffusers>=0.19.3' 'stable_fast-1.0.0+torch211cu121-cp39-cp39-win_amd64.whl'
Looking in indexes: https://download.pytorch.org/whl/cu121

but it says (i'm on windows): 
ERROR: stable_fast-1.0.0+torch211cu121-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.

**Comment by Nicoolodion2** [comment]
> Would be awesome to have a prestartup_script.py file to install all the requirements needed to get this running. I have tried (after downloading the whl file):
> 
> pip3 install --index-url https://download.pytorch.org/whl/cu121 'torch>=2.1.0' 'xformers>=0.0.22' 'triton>=2.1.0' 'diffusers>=0.19.3' 'stable_fast-1.0.0+torch211cu121-cp39-cp39-win_amd64.whl' Looking in indexes: https://download.pytorch.org/whl/cu121
> 
> but it says (i'm on windows): ERROR: stable_fast-1.0.0+torch211cu121-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.

Okay, first of all: "triton" us a Linux thing I believe. That should even be here.
You are also downloading weird conflicts with this. You are downloading torch 2.1.0, but using a 2.1.1 wheel that is probably nor compatible. Are you also sure you actually have this cuda version installed? You can check that by entering `nvcc --version` in cmd.

**Comment by p80ric** [comment]
this is what comfy prints out during boot:
xformers version: 0.0.22.post7
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Torch version: 2.1.0+cu121

So seems like i have torch vision 2.1.0 + cu 121

I just tried to follow the installation guide of the stable fast page but seems like it needs some updates. How should it work with my setup ?

**Comment by Nicoolodion2** [comment]
Okay... It seems like you don't have cuda installed (I guess so because the command doesn't work) Install it over this link: [https://developer.nvidia.com/cuda-12-1-0-download-archive?target_os=Windows](cuda 12.1)
That could be the problem... But I gotta say that it was hard for me to install to. If that doesn't work you can download all the wheels and see which start and which not xD

**Comment by p80ric** [comment]
Thank's for your advice, i feel its a super cool thing but it would need some love to make it more accessible for normal ppl. Ill try it out..

**Comment by dancemanUK** [comment]
windows use  
https://github.com/chengzeyi/stable-fast/releases/tag/v1.0.1
